dataset_dir: ../ffhq
log_dir: ../log
nz: 512
style_depth: 8
const_channel: 512
lr: 0.001
betas: [0.0, 0.99]
eps: 1.0e-8
image_size: 4
batch_size: {'8':128, '16':64, '32':32, '64':16, '128':8, '256':4, '512':2, '1024':1}
lrs: {'128':0.0015, '256':0.002, '512':0.003, '1024':0.003}
generator_channels: [512, 512, 512, 512, 512, 256, 128, 64, 32, 16]
discriminator_channels: [512, 512, 512, 512, 512, 256, 128, 64, 32, 16]
log_iter: 100
phase_iter: 600000
n_cpu: {'8': 32, '16':32, '32':16, '64': 8, '128':4, '256':2, '512':0, '1024':0}
opt_level: O0

